### ISSUE TITLE
running on mac os -x El Capitan I get an error

### ISSUE THREAD

**Issue by msmithuxdesign** [kauffecup/react-redux-webpack-boilerplate#1]
When running in dev or build mode I get the following error...
Any ideas?
to be executed: node server/app.js 
/Users/marksmith/Dropbox/ReactRedux/gitReact/react-redux-webpack-boilerplate-master/server/app.js:37
app.listen(app.get('port'), () => {
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! boilerplate@0.0.1 dev: `better-npm-run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boilerplate@0.0.1 dev script 'better-npm-run dev'.
npm ERR! This is most likely a problem with the boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by kauffecup** [comment]
sorry for the late response!

looks like you're using an older version of node. make sure to be using node > 6.0.0 (you're on v0.12.0)
